apiVersion: v1
kind: Pod  
metadata:
  name: calculator  
  labels:
    app: calculator
spec:
  containers:
  - name: calculator
    image: insang/calculator-m1:v0
    ports:
     - containerPort: 8080
   