apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        imagePullPolicy: Always
        image: insang/calculator-m1:v0
        ports:
        - containerPort: 8080
        readinessProbe: # 요청을 처리할 준비가 되었는지 체크
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10