apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: web-calculator
  ports:
    - port: 8080
      targetPort: 8080 #option
      nodePort: 30007 #option
  type: NodePort