apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: web-calculator
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web-calculator
  template:
    metadata:
      labels:
        app: web-calculator
    spec:
      containers:
      - name: calculator
        image: insang/calculator-m1:v1
        ports:
        - containerPort: 8080